[DoNotCarryForward] Implement Wayland dmabuf approach.
This patch makes it possible to run Wayland backend with a separate gpu process.
That is, WaylandConnection is not available on the GPU process side
and so buffers cannot be created that way.

To overcome this, a Wayland dmabuf based approach is used:
 - On the gpu process side, gl::Surfaceless is used, which is
   implemented by GbmSurfaceless. It differs from the one provided by
   the Ozone/Gbm backend (the difference is that there are no frame
   buffers, because DRM render node is used instead.) Basically,
   on the GPU side, a gbm_bo buffer is created and its file descriptor is
   shared with the WaylandConnection, which then imports a wl_buffer and attaches
   it to a requested surface.

TL:DR;
 - There are two communicating parties - WaylandConnection, which establishes
   a connection with Wayland, and a WaylandConnectionProxy, which serves
   the GPU process with a forwarding mojo connection to the WaylandConnection.
   In single process mode, WaylandConnectionProxy just forwards calls to
   WaylandConnection, and GLSurfaceEGL is used. In a multi process mode,
   the l::Surfaceless and dmabuf based approach is used instead.

 - The communication is established in the following way:
   when WaylandConnectionConnector receives a OnGpuServiceLaunched,
   it binds WaylandConnection and WaylandConnectionProxy interfaces, and
   calls to WaylandConnectionProxy to set a mojo ptr to the WaylandConnection.
   The WaylandConnectionProxy receives the pointer, stores it and also stores
   a task runner to make sure mojo is called on the right sequence.

How buffers are created:
 - Basically, the GPU process doesn't know about Wayland. What it does
   is that it creates a GbmBuffer utilizing a DRM render node (it can't use
   a drm card device, because authentication requires master access), takes
   a gbm_bo file descriptor and shares it via a mojo call with the
   WaylandConnection, which then uses the zwp_linux_dmabuf interface to
   import a wl_buffer, which can be attached to a needed WaylandWindow
   and commit-ed to show contents. That is, the gbm framework is used to share buffers
   between the browser and the GPU process, where the browser process can read from them and
   the GPU process is able to read and write using gl commands.

How buffers are committed:
 - GbmSurfaceless uses a normal procedure and submits frames on
   SwapBuffersAsync call: a frame is created and scheduled as an overlay plane,
   once scheduling is done, a widget is taken from that pending plane and
   WaylandConnection::ScheduleBufferSwap is called. In order to specify, which
   wl_buffer must be used, gbm bo handle is used as a buffer id.
   Once the WaylandConnection receives a buffer swap call, it finds a buffer by a
   buffer id and attaches that buffer to a WaylandWindow, which is also found
   by a widget passed to it. PresentationCallback is not used and will be
   enabled in the future.

The missing feature is the software rasterization. That is, the gbm buffers cannot be
mmap'ed using unix mmap method. Thus, it's impossible to get a mapped memory range and let the cpu
write to it. I think this problem can be resolved in the downstream projects in different ways
but these solutions are not generic enough to be upstreamed.

Another missing feature is presentation feedback. This will be implemented in follow up
CLs.

COMPILE= use use_system_minigbm=true, use_system_libdrm=true, ozone_platform_wayland=true
TEST=run and compile ozone/wayland.

Cq-Include-Trybots: luci.chromium.try:android_optional_gpu_tests_rel;luci.chromium.try:linux_optional_gpu_tests_rel;luci.chromium.try:mac_optional_gpu_tests_rel;luci.chromium.try:win_optional_gpu_tests_rel
Change-Id: Id351edd9883a765d3e549543a50175299108c6ab

fixup! [DoNotCarryForward] Implement Wayland dmabuf approach.

Fixed Compilation Error
../../ui/ozone/platform/wayland/drm/gbm_pixmap_wayland.h:22:26: note:
[chromium-style] 'GbmPixmapWayland' inherits from 'gfx::NativePixmap' here
class GbmPixmapWayland : public gfx::NativePixmap {